# ReadTheDocs configuration file

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.14"

python:
  version: "3.14"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub
